### ISSUE TITLE
Connection to Discord breaks after a while

### ISSUE THREAD

**Issue by soopyc** [soopyc/discordrp-mpris#2]
### Relevant log lines
```
2022-08-31 12:50:02,835 | DEBUG    | sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 442908, 'activity': {'details': 'Meruru - YOU', 'timestamps': {'start': 1661921336}, 'state': 'on Internet Pajamas Party!', 'assets': {'large_text': 'Spotify', 'large_image': 'miku', 'small_image': 'playing', 'small_text': 'Playing [1:06/2:42]'}}}, 'nonce': 'ef411553-30ce-4236-847c-f41f3d48ccf4'} [discord_rpc.async_]
2022-08-31 12:50:02,838 | DEBUG    | received {'code': 1003, 'message': 'data size does not match what was received'} [discord_rpc.async_]
2022-08-31 12:50:02,843 | WARNING  | received unexpected reply; (2, {'code': 1003, 'message': 'data size does not match what was received'}) [discord_rpc.async_]
```

**Comment by soopyc** [comment]
opened an issue here as i'm not sure if it's related to the changes i've made. will test with upstream source later to see if i have to open an issue in the upstream repo.

Might be related to FichteFoll/discordrp-mpris' issue 11

**Comment by soopyc** [comment]
Discord debug logs on default setting yields no useful result.
```
[RPCServer:IPC] Socket Close: 4552
```

**Comment by soopyc** [comment]
Reproducible on upstream repo
```
$ git remote -v
origin  https://github.com/fichtefoll/discordrp-mpris (fetch)
origin  https://github.com/fichtefoll/discordrp-mpris (push)
$ git describe --all --long
tags/v0.3.3-0-g911aa5a
```
Log snippet
```
2022-09-01 23:09:26,063 | DEBUG    | No value for key 'player.Spotify.show_time' [discordrp_mpris.config]
2022-09-01 23:09:26,063 | DEBUG    | sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 5536, 'activity': {'details': 'Dancing in the Blue\nby whoo', 'timestamps': {'start': 1662044962}, 'state': 'Playing [3:04]', 'assets': {'large_text': 'Spotify (Playing)', 'large_image': 'playing'}}}, 'nonce': '93bc30da-9f2c-4a7e-b83d-7cd7669e4e53'} [discord_rpc.async_]
2022-09-01 23:09:26,064 | DEBUG    | received {'code': 1003, 'message': 'data size does not match what was received'} [discord_rpc.async_]
2022-09-01 23:09:26,064 | WARNING  | received unexpected reply; (2, {'code': 1003, 'message': 'data size does not match what was received'}) [discord_rpc.async_]
2022-09-01 23:09:26,064 | DEBUG    | Connection error during tick [discordrp_mpris.__main__]
Traceback (most recent call last):
  File "/home/sophie/build/discordrp-mpris/venv/lib/python3.10/site-packages/discordrp_mpris/__main__.py", line 91, in run
    await self.tick()
  File "/home/sophie/build/discordrp-mpris/venv/lib/python3.10/site-packages/discordrp_mpris/__main__.py", line 182, in tick
    op_recv, result = await self.discord.set_activity(activity)
  File "/home/sophie/build/discordrp-mpris/venv/lib/python3.10/site-packages/discord_rpc/async_.py", line 176, in set_activity
    return await self.send_recv(data)
  File "/home/sophie/build/discordrp-mpris/venv/lib/python3.10/site-packages/discord_rpc/async_.py", line 144, in send_recv
    reply = await self.recv()
  File "/home/sophie/build/discordrp-mpris/venv/lib/python3.10/site-packages/discord_rpc/async_.py", line 163, in recv
    op, length = await self._recv_header()
  File "/home/sophie/build/discordrp-mpris/venv/lib/python3.10/site-packages/discord_rpc/async_.py", line 105, in _recv_header
    header = await self._recv_exactly(8)
  File "/home/sophie/build/discordrp-mpris/venv/lib/python3.10/site-packages/discord_rpc/async_.py", line 252, in _recv_exactly
    return await self.reader.readexactly(size)
  File "/usr/lib/python3.10/asyncio/streams.py", line 708, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.10/asyncio/streams.py", line 502, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 854, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

```

**Comment by soopyc** [comment]
Verbose logging provides no useful information either.
```
[RPCServer:IPC] Socket Close: 5
[GatewaySocket] ~> 3 {status: "dnd", since: 0, activities: Array(1), afk: false}
    activities: Array(1)
      0:
        emoji: {id: null, name: "👗", animated: false}
        name: "Custom Status"
        state: "(>﹏<)"
        type: 4
    length: 1
    afk: false
    since: 0
    status: "dnd"
```

**Comment by soopyc** [comment]
honestly this might just be a spotify issue (i disconnected my spotify so i need to use this)

will test with another player.

  the main problem is that the program couldn't reconnect to discord automatically after a 1003. if i couldn't figure out what's causing the error i'll just kill the program when it encounters the 1003.

**Comment by soopyc** [comment]
reasonably sure this is a spotify specific problem. 
![image](https://user-images.githubusercontent.com/13762043/188165117-45971a0a-a708-4cc8-bf12-74d6f2911861.png)

**Comment by soopyc** [comment]
```
2022-09-02 22:42:49,084 | DEBUG    | sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 88420, 'activity': {'details': 'TRICK or HOLIC - TRUSTRICK', 'timestamps': {'start': 1662110019}, 'state': 'on Eternity', 'assets': {'large_text': 'mpv', 'large_image': 'miku', 'small_image': 'playing', 'small_text': 'Playing [5:29:09/5:29:17]'}}}, 'nonce': '02a3bfb1-e47c-49c4-843f-d458be5957f5'} [discord_rpc.async_]
2022-09-02 22:42:49,085 | DEBUG    | received {'code': 1003, 'message': 'data size does not match what was received'} [discord_rpc.async_]
2022-09-02 22:42:49,085 | WARNING  | received unexpected reply; (2, {'code': 1003, 'message': 'data size does not match what was received'}) [discord_rpc.async_]
2022-09-02 22:42:49,085 | DEBUG    | Connection error during tick [discordrp_mpris.__main__]
Traceback (most recent call last):
  File "/home/sophie/fuck/discordrp-mpris/discordrp_mpris/__main__.py", line 91, in run
    await self.tick()
  File "/home/sophie/fuck/discordrp-mpris/discordrp_mpris/__main__.py", line 201, in tick
    op_recv, result = await self.discord.set_activity(activity)
  File "/home/sophie/fuck/discordrp-mpris/discord_rpc/async_.py", line 176, in set_activity
    return await self.send_recv(data)
  File "/home/sophie/fuck/discordrp-mpris/discord_rpc/async_.py", line 144, in send_recv
    reply = await self.recv()
  File "/home/sophie/fuck/discordrp-mpris/discord_rpc/async_.py", line 163, in recv
    op, length = await self._recv_header()
  File "/home/sophie/fuck/discordrp-mpris/discord_rpc/async_.py", line 105, in _recv_header
    header = await self._recv_exactly(8)
  File "/home/sophie/fuck/discordrp-mpris/discord_rpc/async_.py", line 252, in _recv_exactly
    return await self.reader.readexactly(size)
  File "/usr/lib/python3.10/asyncio/streams.py", line 708, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.10/asyncio/streams.py", line 502, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 854, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
2022-09-02 22:42:49,089 | INFO     | Connection to Discord client lost. Reconnecting... [discordrp_mpris.__main__]
```
I was wrong
